### ISSUE TITLE
nokogiri - can we use 1.6.2 instead?

### ISSUE THREAD

**Issue by newgoliath** [glittergallery/GlitterGallery#149]
1.6.1 will not build on my system, but 1.6.2 does just fine.  Has anyone tried it?

**Comment by sarupbanskota** [comment]
https://github.com/glittergallery/GlitterGallery/commit/6c74a024b0152067586d0d4ba2570d613bcb08d8#diff-e79a60dc6b85309ae70a6ea8261eaf95R134 should look after it.
