### ISSUE TITLE
Improve Issue ID lookup

### ISSUE THREAD

**Issue by rohitpaulk** [glittergallery/GlitterGallery#151]
Currently, the Issue subIDs are found by searching an array of the project's issues IDs, sorting and then finding the position of a certain issue. It's likely to be faster if we store the issue subID in our database. 

[Here](http://rohitpaulk.roon.io/title-undecided)'s a blogpost about this if you'd like to read more.

**Comment by EmilyDirsh** [comment]
@rohitpaulk - is this still relevant? Just trying to clean up the issue tracker...

**Comment by rohitpaulk** [comment]
It is relevant, yes. :)

**Comment by EmilyDirsh** [comment]
Do we need to discuss it more, or are we just waiting on implementation?

**Comment by rohitpaulk** [comment]
We discussed this over email long ago. From the blog post: 

> Add two more columns to your database. One for the sub_id on the issue model, and an increment counter on the project model.

**Comment by EmilyDirsh** [comment]
@rohitpaulk - I'm thinking this might be a good first bug - what do you think?
