### ISSUE TITLE
Sparkleshare integration

### ISSUE THREAD

**Issue by EmilyDirsh** [glittergallery/GlitterGallery#162]
As a designer using Glitter Gallery
I want to work on my projects locally and have Sparkleshare sync them to Glitter Gallery
So that I don't have to manually sync my projects (or know anything about Git)

_This is dependent on #161, but includes some interface enhancements to make it easier to set up a GG project with Sparkleshare and vice/versa._

**Comment by sonalkr132** [comment]
Can be closed. Now we have sparkleshare support.
