### ISSUE TITLE
Simplify comments using polymorphic associations syntax

### ISSUE THREAD

**Issue by rohitpaulk** [glittergallery/GlitterGallery#185]
We have the schema for a polymorphic association (`polycomment_id` and `polycomment_type`), but we aren't making use of the rails syntactic sugar when working with comments in controllers.

http://guides.rubyonrails.org/association_basics.html#polymorphic-associations

**Comment by sarupbanskota** [comment]
@rohitpaulk I'm thinking we can assign this bug to the next person who asks for a starting point.

**Comment by rohitpaulk** [comment]
I don't think that we should 'assign' simple bugs at all. If we start assigning people bugs this small, it's just going to be more work for us - pinging them to ask if they've worked on it etc. 

Assigning does make sense for bigger features, stuff that would take time to work on :)

**Comment by sarupbanskota** [comment]
by *assign*, I meant more like direct them to this, we don't follow up with them if there's no news of course.

or are you suggesting we look after these bugs ourselves?

**Comment by rohitpaulk** [comment]
> by assign, I meant more like direct them to this, we don't follow up with them if there's no news of course.

Oh, then it's ok. I thought you were talking about locking issues and preventing others from working on them. 

> or are you suggesting we look after these bugs ourselves?

No no, not at all :)

**Comment by rohitpaulk** [comment]
https://github.com/glittergallery/GlitterGallery/pull/254#issuecomment-82853815

Closing.
