### ISSUE TITLE
Dealing with thumbnails

### ISSUE THREAD

**Issue by sarupbanskota** [glittergallery/GlitterGallery#200]
What are your opinions on this? Do we generate thumbnails per commit? Do we save them within the satellite repo? Do we save them elsewhere? I wouldn't keep them on the satellite repo, and would create a thumbnails dir along with satellite and bare repo. For each commit that takes place, I'd generate thumbnails and place them within a dir with the same tree hash as that of the commit's. 

The other option is to do thumbnails on the fly.. ie on the thumbnails dir, generate thumbnails as the page request is made, but that would be a slow approach imo. I've writing this super simple gem called `phototrim`, we could use that for now.

**Comment by EmilyDirsh** [comment]
IMO, thumbnails are for GG use, and we don't need to pollute the repo with them. +1 to the separate thumbnails dir and generating and saving a thumb whenever a commit is made. We can use the commit id to name them.

**Comment by EmilyDirsh** [comment]
I believe this fixed with the referenced PRs.
