### ISSUE TITLE
When locally trying to "Find Project" while logged in ,gives out an Error 

### ISSUE THREAD

**Issue by hTrap** [glittergallery/GlitterGallery#202]
Error:
ActiveRecord::StatementInvalid at /inspire
SQLite3::SQLException: no such column: TRUE: SELECT COUNT(*) FROM "projects"  WHERE (private IS NOT TRUE AND user_id <> 3)

This line uses  an sql query interface
https://github.com/glittergallery/GlitterGallery/blame/master/app/controllers/projects_controller.rb#L13

while it should have been using a rails query interface because sqlite is used as a development databse

**Comment by rohitpaulk** [comment]
@hTrap - PRs are welcome :)
