### ISSUE TITLE
Error while trying to create a project

### ISSUE THREAD

**Issue by sbagroy986** [glittergallery/GlitterGallery#206]
I keep getting this when I try to create a project: http://gyazo.com/8d575e674154cf98b78115c1dd3348e6
Probably a problem with the latest merge.

**Comment by rohitpaulk** [comment]
That's a screenshot of a code diff. Can you provide more details on the error?

**Comment by sbagroy986** [comment]
Sorry. Put the wrong link there:  http://gyazo.com/c2b1eafd3c4319b5fc2e2a189b3c2fa9

**Comment by sarupbanskota** [comment]
Could you reproduce it? What were you trying to do, what did you expect, what happened?

**Comment by sbagroy986** [comment]
I'm creating my first project ( /projects/new? ). I give it a name and I click on Public or Private, and this comes up.

**Comment by sbagroy986** [comment]
If I roll back to '26b8062 changing sql type query method to rails type' and I don't face this problem.

**Comment by sarupbanskota** [comment]
alright, I have started a thread that will hopefully address it.


Sarup

**Comment by rohitpaulk** [comment]
I don't think that this has anything to do with #203. #203 wasn't accurate in itself, but I don't see anything there that would cause the error mentioned here. 

I don't have time to debug where this bug was introduced, but I think that #208 should fix it :)

**Comment by rohitpaulk** [comment]
And this is something that **should** be covered by specs, I certainly remember writing them.

**Comment by rohitpaulk** [comment]
Current status on Master - 
`45 examples, 16 failures, 5 pending`

on #208 - 
`45 examples, 5 failures, 5 pending`

**Comment by rohitpaulk** [comment]
I made a mistake modifying travis.yml a while ago. Travis runs `rake test`, we need `rspec`. No wonder Travis has been green inspite of such serious problems in our app.

**Comment by sarupbanskota** [comment]
oh no. should we revert back my PR and I'll investigate if I have broken
something?


Sarup

**Comment by rohitpaulk** [comment]
There's a lot of work in there, it'd be better to just fix the bugs in a PR - preferably in #208 itself.

**Comment by sarupbanskota** [comment]
@sbagroy986 with the two new merged PRs, does it fix your problem? If so, we can close this.

**Comment by sbagroy986** [comment]
Yes it does. Thanks.
