### ISSUE TITLE
Facebook OAuth parameter app_id is required FAILURE

### ISSUE THREAD

**Issue by chi6rag** [glittergallery/GlitterGallery#217]
![gg_fb_oauth_id_miss](https://cloud.githubusercontent.com/assets/6065869/6501728/f327865a-c341-11e4-9afd-dadcc44884af.png)

**Comment by chi6rag** [comment]
this error is in production
same exists fot github and linkedin

**Comment by sarupbanskota** [comment]
Have you set env variables?

On Thursday, March 5, 2015, Chirag Aggarwal <notifications@github.com>
wrote:

> this error is in production
> same exists fot github and linkedin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/glittergallery/GlitterGallery/issues/217#issuecomment-77327017>
> .
>


-- 

Sarup

**Comment by chi6rag** [comment]
http://glittergallery-ropaku.rhcloud.com/

this one, maybe Emily has access to this

**Comment by rohitpaulk** [comment]
Thats my demo, its not maintained.
