### ISSUE TITLE
Error while creating new project (Local)

### ISSUE THREAD

**Issue by mecyborg** [glittergallery/GlitterGallery#219]
Failed to make directory 'public/data': File exists
http://awesomescreenshot.com/0214kbo5fe

**Comment by Alwahsh** [comment]
rename the file data to data2 while developing then rename that back to data after you finish before pushing...
or go to config/initializers/0_glitterconfig.rb and edit line 39, replace data with anything else but don't forget to adjust it back before pushing.

**Comment by mecyborg** [comment]
Ok. Will look into this !

**Comment by Alwahsh** [comment]
@sarupbanskota  @rohitpaulk I think this is the third report of that issue... I suggest that for development, it is made developmentdata as it's done in the test environment.

**Comment by rohitpaulk** [comment]
@Alwahsh - The correct way to go about it would be to

- Delete the `public/data` symlink.
- Modify the default config in `config/initializers/0_glitterconfig.rb` so that the repo works as-is on Openshift. (Use the `OPENSHIFT_DATA_DIR`) variable.

**Comment by mecyborg** [comment]
@rohitpaulk this is a better solution. Thanks.

**Comment by mecyborg** [comment]
Renaming the 'data' fixed this temporarily. But we should find a permanent way to fix this issue.

**Comment by rohitpaulk** [comment]
> But we should find a permanent way to fix this issue.

What I mentioned above **is** a permanent way to fix the issue.

**Comment by mecyborg** [comment]
Then we should commit this.

**Comment by rohitpaulk** [comment]
@mecyborg - Feel free to send in a PR. :)

**Comment by mecyborg** [comment]
PR request is sent. Please verify.
