### ISSUE TITLE
the demo is down?

### ISSUE THREAD

**Issue by tvvocold** [glittergallery/GlitterGallery#224]
503 Service Unavailable

**Comment by rohitpaulk** [comment]
Yes, I don't maintain [my demo](glittergallery-ropaku.rhcloud.com) anymore. We should create an official demo, anyone who'd like to volunteer - please do.

**Comment by EmilyDirsh** [comment]
I'll set one up on my OpenShift account and connect the glittergallery.net domain. Should have been using it from the start, probably :P

**Comment by Alwahsh** [comment]
I've set up one if you want to use it...
http://glittergallery-themonster.rhcloud.com/

**Comment by EmilyDirsh** [comment]
@Alwahsh thanks, but I need to own the demo in order to set up the alias.

**Comment by sarupbanskota** [comment]
@EmilyDirsh - could you please look after this when you're around the next time? We should keep at least one demo live on the readme, or it leads to more emails :) also, maybe should also set a hook off master and leave a note on the readme about it.

**Comment by tvvocold** [comment]
BTW, if there are no HTTP connections to your application for 24 hours, OpenShift idles the gear. So u can use uptimerobot.com to GET ur alias every 5 min to avoid the idle.

**Comment by rohitpaulk** [comment]
> BTW, if there are no HTTP connections to your application for 24 hours, OpenShift idles the gear. So u can use uptimerobot.com to GET ur alias every 5 min to avoid the idle.

This only happens on free gears. If we're using free gears and our app is not being hit every 24 hours, we shouldn't try to game the system by pinging it every 5 mins, rather just make do the ~30s lag when the first request goes through.

**Comment by EmilyDirsh** [comment]
Alright, demo is up at demo.glittergallery.net, and the landing page is updated to point to the new demo.
