### ISSUE TITLE
irreversible migrations

### ISSUE THREAD

**Issue by sonalkr132** [glittergallery/GlitterGallery#230]
"20150304042821_make_projects_public_by_default" was irreversible, I fixed that. "20140518213805_add_devise_to_users" is also irreversible. I am not sure if I should make changes to its down method. Are we using it as fail safe?

**Comment by EmilyDirsh** [comment]
20140518213805_add_devise_to_users is nearly 10 months old. I wouldn't worry about making that reversible.
