### ISSUE TITLE
New Comment AJAX not working

### ISSUE THREAD

**Issue by mecyborg** [glittergallery/GlitterGallery#232]
After adding new comment, it is not updated. Have to refresh the page to view new comment.

**Comment by sbagroy986** [comment]
Okay so the problem here isn't the AJAX. Its most probably the ActionMailer. 
If you comment out the following chunk of code
![screenshot from 2015-03-09 15 21 36](https://cloud.githubusercontent.com/assets/7946556/6552814/0d21dd40-c670-11e4-9c0f-2fa6db8f1f9a.png)

and the "Issue?" line in _comment.html.haml,  the comments work fine. 
I'll try and look into it in a bit.

**Comment by mecyborg** [comment]
Comments are working fine. Its just the js which is not rendering.

**Comment by sbagroy986** [comment]
I meant the comments would render if you do what I mentioned above :)

**Comment by mecyborg** [comment]
Ok, thanks ! I guess this is the ActionMailer as you said. :+1:

**Comment by sonalkr132** [comment]
I have already fixed it, look at #226 
Now, there is another thing which is not working.. that is comments from others on your on your repo. This one might have something to do with actionmailer. I guess we can look into that?

**Comment by EmilyDirsh** [comment]
The notification should be triggered in the background, and non-blocking. Anyone who wants to tackle this, just claim it.

**Comment by Alwahsh** [comment]
@EmilyDirsh Do you mean creating the notification object itself should be done in the background or sending it to the user? if you mean the latter, then it's already done in #233 :)

**Comment by sonalkr132** [comment]
I have suggestion related to this. Comment made on someone else's repo don't show right away, cause development.rb isn't configured properly for sending mails. [letter_opener](https://github.com/ryanb/letter_opener) handles it quite well. It sends kinda stubed email right in the browser and doesn't actually send it. I integrated it this app and it solved the issue of ajax call not completing. 
What do you guys think?

**Comment by EmilyDirsh** [comment]
@Alwahsh I meant sending the email to the user. The non-blocking part is important too. Some environments may not have working outgoing email, so we don't want to block the rest of the execution because email doesn't work.

**Comment by Alwahsh** [comment]
@EmilyDirsh Great.. That's exactly what I did using Delayed job. The PR is not ready to be merged yet, but I'm trying to finish it ASAP :)

**Comment by EmilyDirsh** [comment]
@sonalkr132 something like that would be good for testing email during development, but it's not going to fix the bug outside of a dev environment. Also, according to the home page, letter_opener only works in a local environment, I'd prefer looking into one of their suggestions - http://mailcatcher.me/ - for a more flexible solution.

**Comment by EmilyDirsh** [comment]
@Alwahsh great to hear. Delayed Job will be a nice enhancement, both for email and image processing.

**Comment by chi6rag** [comment]
I believe the problem still persists.
Have a look at this:

![comments_wont_work](http://res.cloudinary.com/chi6rag/image/upload/v1432205216/GlitterGallery/gg__buggy_self_comments.png)

**Comment by sonalkr132** [comment]
You are looking at demo. It is not always up to date with master. Can you please pull [master](https://github.com/glittergallery/GlitterGallery.git) and check if problem exists there? I don't think it should.

**Comment by sonalkr132** [comment]
@chi6rag  check this: http://demo-glitterfollowers.rhcloud.com/ Even this is not master, so you might not see all the features. However, the two issues you mentioned are fixed here.

Also, our work with comments is not done yet. Read [this](https://github.com/glittergallery/GlitterGallery/pull/254#issuecomment-104000371) comment for further info.
