### ISSUE TITLE
Users can update pictures in projects of the other users

### ISSUE THREAD

**Issue by sbagroy986** [glittergallery/GlitterGallery#234]
Basically, I can edit any project of any other user right now because it gives me the 'Update' option.
eg:
![8935c981c685653400236da20e72a937](https://cloud.githubusercontent.com/assets/7946556/6557766/8b81c09c-c69d-11e4-8554-6a1c2119d5e0.png)

I am logged in as 'sba23' but can update a picture in the user 'sbaa23's repo.
Is this how its supposed to work? I already fixed this locally but I wasn't too sure how the system is supposed to work.

**Comment by EmilyDirsh** [comment]
This is definitely a bug. Only the owner (and maybe in the future, collaborators) should be able to update a project.
