### ISSUE TITLE
[RFE] Fork "network" view

### ISSUE THREAD

**Issue by EmilyDirsh** [glittergallery/GlitterGallery#237]
Given the changes in #231, it'd be nice to have a way to display the relationships between an original project and all the downstream forks of that project, whether forked from the original or another fork. 

This is similar to the GitHub network feature.

I'd recommend the [Ancestry](https://github.com/stefankroes/ancestry) gem for the implementation.

**Comment by sarupbanskota** [comment]
yup among other ideas, just noting:

* alert user with what's happening
* provide user with choices

**Comment by Alwahsh** [comment]
What should happen when a project is deleted? Should his children be mapped to his parent? what if it was the root project? Each of its children becomes root?

**Comment by EmilyDirsh** [comment]
that's a good question. I think we want to preserve the relationship between the branches. I think we really need a soft delete for this. What I mean by that is when a user deletes a project, instead of removing it from the database, we mark it as deleted. We can still remove the repo, and we can remove the list of followers, and anything else that makes sense, but we keep the entry in the database along with at least the name and owner, so we can still refer to it. 

If we did this, and someone tried to access a deleted repo, we could give them a more meaningful message than a 404 - something like 'This project was removed by its owner'

**Comment by Alwahsh** [comment]
@EmilyDirsh sorry for opening this again but what should happen if a person had deleted a project and then decided to create one with the same name. A possible option would be to really delete the soft deleted one but then we go back to deciding what to do with his children. Another option is to update the soft deleted one with the info of the new one and restore it but then it would have wrong children who didn't come from it. The third option is to not allow the user to create a new one with the same name as a deleted one which seems the most reasonable to me. What do you think?

**Comment by EmilyDirsh** [comment]
@Alwahsh not allowing the user to create one with the same name seems reasonable to me. At least for now.

**Comment by charithhewage** [comment]
I just tried this in Github using two accounts. In Github, repo owner can delete it, but forked items will be changed forked to own repos. Please find the attachment bellow. i think we can implement something like this. :)
![fork function in github](https://cloud.githubusercontent.com/assets/6915496/6710772/f6014f70-cda8-11e4-8a7f-56bc44983744.jpg)
