### ISSUE TITLE
[RFE] Container support

### ISSUE THREAD

**Issue by EmilyDirsh** [glittergallery/GlitterGallery#239]
tl;dr: Containers are awesome, and GlitterGallery should work in containers.

Containers are becoming increasingly important to IT infrastructures, and therefore to developers and ops folks deploying applications using containers. OpenShift v3 is in beta now and is completely containerized. Being able to run Glitter Gallery in a docker container will allow us a really easy way to distribute GG, and for our contributors and users, easier set up of development environments and easier deployment.

Check out the interactive tutorial for the basics: https://www.docker.com/tryit/

**Comment by EmilyDirsh** [comment]
@sarupbanskota I know you've started working on this some. Can you track your progress in this issue? If you want to continue working on it, assign it to yourself. If you don't have time, let's just leave it open for whoever wants to pick it up.

**Comment by sarupbanskota** [comment]
I'll leave it open. I have inconsistent bursts of time available, don't want to be a blocker :)

**Comment by ChenLiZhan** [comment]
I have some experience on Docker, can we discuss more detail :)

**Comment by ChenLiZhan** [comment]
I think you want GG becomes a dockerize application! Is there anything that might I need to aware?

**Comment by EmilyDirsh** [comment]
#259 is addressing this
