### ISSUE TITLE
Gravatar not working

### ISSUE THREAD

**Issue by sonalkr132** [glittergallery/GlitterGallery#241]
application_helper.rb has defined gravatar with: 
```Ruby
      tag :image, src: "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{gravatar_size}&d=#{CGI.escape(root_url + default)}"
```
Now problem is that default image for avatar has to be online. Read [here](https://en.gravatar.com/site/implement/images#default-image) 

Suggestions?

**Comment by Alwahsh** [comment]
in production, the image is online :)

**Comment by sonalkr132** [comment]
Oh sorry! Didn't think of it that way.
