### ISSUE TITLE
Resolving the assets issue

### ISSUE THREAD

**Issue by Alwahsh** [glittergallery/GlitterGallery#243]
If I understood what's going on correctly, openshift has problems with compiling our assets on deployment.
The current solution is to compile the assets manually whenever we introduce a change to the assets and push it with the source code. This makes the repo keep getting bigger and bigger with every simple change in the assets.

If we can't resolve the openshift issue with compilation. I suggest that the user is advised to do the compilation thing by himself instead of adding them to the repo like now.

**Comment by rohitpaulk** [comment]
IIRC the precompilation isn't because Openshift had problems, it was because we thought that our builds were taking too long. Turns out it wasn't the asset precompilation that was slowing us down, it was bundle install. 

I agree, we shouldn't keep assets in the repo. Configuring Openshift to compile them on deployment seems like the right way to go.

**Comment by EmilyDirsh** [comment]
OpenShift _does_ compile them on deployment by default. If they're already compiled (like ours are) then rails doesn't recompile. Switching the gem source from rubygems.org to the [OpenShift mirror] (https://developers.openshift.com/en/ruby-getting-started.html#_ruby_mirror) really speeds up builds. It'd be nice to automatically switch it when deploying to OpenShift - using one of the hooks - but for now, we should at least document it.

**Comment by Alwahsh** [comment]
@rohitpaulk  Thanks for explaining that :)

@EmilyDirsh but the repo contains the marker `disable_asset_compilation` which seems to be the reason why openshift doesn't compile them... I thought you wanted to disable it because of some problem with openshift.
Now that I know the reason... Should we remove the assets folder and the openshift marker from the repo?

**Comment by EmilyDirsh** [comment]
@Alwahsh yep, that's right.
