### ISSUE TITLE
Profile page with notification link

### ISSUE THREAD

**Issue by philippneugebauer** [glittergallery/GlitterGallery#249]
Is that explicitly wanted that get directed to a new page and losing the context?

I was really confused after I have seen that and from the usability point that is not a good idea in my opinion

**Comment by EmilyDirsh** [comment]
Could you add some details about this? What action does this happen on, what context is lost? Thanks!

**Comment by philippneugebauer** [comment]
I have fixed it in my pull request.

I meant, that you lose the context when you click on notification in your profile area, while the head bar still appears at the user profile and the project menu

**Comment by EmilyDirsh** [comment]
@philippneugebauer okay, that makes more sense. It's probably an oversight.
