### ISSUE TITLE
Can't start server or tests due to logger error

### ISSUE THREAD

**Issue by philippneugebauer** [glittergallery/GlitterGallery#251]
When I try to start my environment, I always get a `NoMethodError: undefined method `logger=' for #<OmniAuth::Configuration:0x00000003078e80>`

Can you confirm that? How do you avoid that?

**Comment by Alwahsh** [comment]
I'd say that your work on #250 made that. Try to do it from the master branch and it should work fine :)

**Comment by philippneugebauer** [comment]
Yeah, you are right
