### ISSUE TITLE
Add a code style linter to Travis

### ISSUE THREAD

**Issue by rohitpaulk** [glittergallery/GlitterGallery#258]
This will involve a lot of work correcting the existing codebase, but it'll be worth it.

The most popular seems to be https://github.com/bbatsov/rubocop. We won't need all the Rails specific checks, just basic code style.

**Comment by sonalkr132** [comment]
I know I need it more badly that anyone -_- 
Any useful links? also we should have wiki for coding style and best practices for noobs like me :stuck_out_tongue_closed_eyes:

**Comment by rohitpaulk** [comment]
> Any useful links?

https://github.com/bbatsov/ruby-style-guide

**Comment by sonalkr132** [comment]
yeah I saw that. Actually:

![screenshot from 2015-03-15 12 58 23](https://cloud.githubusercontent.com/assets/7680662/6655300/04f8ea38-cb1f-11e4-9b6c-0abe08f7a878.png)


That is rubocop with all its defaults.we should discuss about defining our own .rubocop.yml file? using [this](https://github.com/openSUSE/osem/blob/master/.rubocop.yml) offenses were reduced to 700

**Comment by EmilyDirsh** [comment]
I'd prefer the rubocop defaults, since that uses the popular style guide that @rohitpaulk referred to above. It's more work to correct the code base, but it means less work defining and maintaining our own style guide, and will ultimately make it easier for new contributors.

**Comment by sonalkr132** [comment]
I was thinking may be first we can write a simple .rubocop.yml, which counts only indentation and other textual offenses and not the coding style. For example by default it counts too long methods as offense, now re factoring them would be quite and involved approac and we have got a good number of long method definitions. Besides that it also counts no documentation as offense, another quite involved process. 
I am not saying we should throw away the defaults for good, I am just saying that we should start from something simple, get our code to pass that and work our way up from there.

**Comment by EmilyDirsh** [comment]
@sonalkr132 I think it's fine to start small - just fix indentation, etc, but I'd like to maintain all the default checks still. For one thing, it's very likely that we'll all forget to go back and add the remaining checks in the future. For another thing, it'd be good to have all new contributions match the default, stricter criteria.

**Comment by sonalkr132** [comment]
I would still suggest, turning some of the offenses off for now would be helpful for anyone who is fixing it. Don't worry that we won't go back to fix the rest of issues, you will have to take my word for it. Besides that we don't need everything of rubocop, for ex: it requires that every class definition has a comment block above it, I don't think anyone does that for rails apps.
New contributers may not follow it from start but again, I don't think we will be able to ask user to follow our coding guidelines and make sure that he does it unless we have fixed our existing code base. Only way to enforce rubocop and make sure that contributers follow is that we add it to travis. But we can't do that unless our existing code passes it.

**Comment by Alwahsh** [comment]
>   it requires that every class definition has a comment block above it, I don't think anyone does that for rails apps.

I strongly disagree with that. These comments are very helpful and allows any one who reads the code to understand what everything does. At least for me, I write a comment above functions I define. Note that these comments are used later by documentation tools like [rdoc](https://github.com/rdoc/rdoc) to generate readable HTML documentation.

**Comment by Alwahsh** [comment]
You were talking about class definitions :). I still find it helpful to have a comment block above models classes at least that describe the tables in the db. Anyways, this is pretty straightforward and you can use a tool to produce it. See [annotate_models](https://github.com/ctran/annotate_models).

**Comment by sonalkr132** [comment]
All I want is that we have our own .rubocop.yml :( everyone else has it [osem](https://github.com/sonalkr132/osem/blob/master/.rubocop.yml), [gitlabhq](https://github.com/gitlabhq/gitlabhq/blob/master/.rubocop.yml), [spree](https://github.com/spree/spree/blob/master/.rubocop.yml), [kandan](https://github.com/kandanapp/kandan/blob/master/app/models/attachment.rb).

I just looked at some more popular apps [errbit](https://github.com/errbit/errbit/blob/master/app/controllers/comments_controller.rb), [selfstarter](https://github.com/lockitron/selfstarter/blob/master/app/models/order.rb) and no one seem to have it implemented. Even the ones I found which had a block comment was [fat_free_crm](https://github.com/fatfreecrm/fat_free_crm/blob/master/app/controllers/comments_controller.rb) and [readmine](https://github.com/edavis10/redmine/blob/master/app/models/change.rb), but their block comment above class isn't very useful or something we need.

>I still find it helpful to have a comment block above models classes at least that describes the tables in 
>the db.

Makes sense tho. I have seen it in some app. They have it in model and at the end.

**Comment by Alwahsh** [comment]
We wouldn't want to have something just because everyone has it. You can learn best practice from those but apply it to the best fit for you. I don't think it's a problem if we have it failing on travis for sometime... At least we can make sure that upcoming modifications won't make the numbers increase ;)

> I just looked at some more popular apps errbit, selfstarter and no one seem to have it implemented.

If it'd be useful for the readability of our app, then I wouldn't care if others don't have it.

**Comment by rohitpaulk** [comment]
I'm reopening this - I only added specs to the models and controllers, as they were the most important. We should also include the ruby files under `spec/`.

**Comment by sonalkr132** [comment]
We can also check haml files with haml-lint if we hook it to github.
