### ISSUE TITLE
Rails default server (WEBrick)

### ISSUE THREAD

**Issue by mecyborg** [glittergallery/GlitterGallery#261]
Currently the GG is running on the default rails server (WEBrick).
As there are many limitations with WEBrick, should we upgrade server to unicorn, thin or puma ?

What do you think ?

**Comment by EmilyDirsh** [comment]
@mecyborg could you give some more details about what limitations WEBrick has vs the other servers you mentioned? Also I think WEBrick is only running in dev and test environments. Given this, is it still important to use something besides WEBrick?

@sarupbanskota, @rohitpaulk - do you guys have any thoughts on this proposal?

**Comment by mecyborg** [comment]
WEBrick is OK for development and testing but for production i think we should switch to other servers. Some of the limitations are, by default WEBrick is single threaded, single process. We can make it multi threaded though. It does not support subdomains. It can't handle longer URLs, if they exceed 2083 chars it will crash.

**Comment by sonalkr132** [comment]
On Openshift we are using passenger, running inside Apache by default.

**Comment by sarupbanskota** [comment]
I honestly don't know much about these servers to have a solid opinion.
That said, I'd like to ask: how does the switching difficulty change if we
were to do it later later, at a point when we're more complex? What parts
of code will change, and how will it affect other dependent parts?

Sarup

**Comment by mecyborg** [comment]
@sarupbanskota there are no difficulties in switching between these servers. It can be easily done by just adding and removing gems for different servers and editing some server configurations.

**Comment by sarupbanskota** [comment]
@mecyborg in that case, I'd say let it stay the way it is for now. When we start to see problems with an active deployment, we'll bring it up again.

**Comment by mecyborg** [comment]
@sarupbanskota ok. We will update the server as when there is any issue.
