### ISSUE TITLE
Updates required on wiki

### ISSUE THREAD

**Issue by sonalkr132** [glittergallery/GlitterGallery#274]
1. Deploying on openshift
  * replace the merged "assets" file with original assests
  * git rm public/index.html
  * git rm app/views/layouts/application.html.erb 

    I don't know if others who deployed had the same issues but it wasted a lot of my time.

2. Handling of secrets
  I am still waiting to hear about [comment](https://github.com/glittergallery/GlitterGallery/pull/255#issuecomment-78468604) Either way we need to update wiki about it

3. Delayed jobs
  * excute  `rake jobs:work` from a separate terminal to launch it in local env

4. Mailcatcher
 * execute: `gem install mailcatcher`
 * Don't add it to gemfile. just run `mailcatcher` to start it
 * Go to "127.0.0.1:1080" to see the mails. See [Details](http://mailcatcher.me/) 

I am sure there are more things which needs to be added. Comment below and we will update everything at once?

**Comment by mecyborg** [comment]
Minor spelling mistake: its ''mailcatcher'' :)

**Comment by Alwahsh** [comment]
> I don't know if others who deployed had the same issues but it wasted a lot of my time.

Yeah, I did... Sorry that I didn't announce it then.. Would've saved you some time.

**Comment by Alwahsh** [comment]
Ah now I remembered why I didn't announce it at that time... The repo had the disable compilation and had the assets in the public folder so it should've worked correctly... I just couldn't upload the assets due to their large size so I had to search for a workaround... Didn't think others will need it.

**Comment by sonalkr132** [comment]
@Alwahsh You have made a few changes related to assets. Did you try to deploy on openshift after that? Do we still need to place the assets folder?

@EmilyDirsh What other updates did you have on your mind when you mentioned it in [this](https://github.com/glittergallery/GlitterGallery/pull/240#issuecomment-83008057) comment?

**Comment by sonalkr132** [comment]
@mecyborg thanks! I updated it.

**Comment by Alwahsh** [comment]
@sonalkr132 I only deleted the public/assets folder.. The only thing I remember that I needed to do is what I advised you to do, remove the full app/assets folder from the default openshift application before merging GG.

I think that should be added. Not sure if that's what you meant by your first point but if so, you don't actually need to replace the merged one with the original one... Just delete the old one before doing git pull. I told you to do so then because you had already pulled :)

**Comment by sonalkr132** [comment]
Correct me if I am wrong, but our **run glittergallery** should look like

3.Clone the application repo: git clone <OpenShift git URL>
4.Change into the cloned directory
5.git rm -r app/assets/
6.Add the GlitterGallery repo: git remote add glitter -m master http://github.com/glittergallery/GlitterGallery.git
7.Pull: git pull -s recursive -X theirs glitter master

**Comment by Alwahsh** [comment]
yeah... I think so

**Comment by sonalkr132** [comment]
I guess it's about time we make changes, if emily has to add something we will add it later.
Just quick question tho.. should we add these to `readme.markdown` or [Usage Instructions](https://github.com/glittergallery/GlitterGallery/wiki/Usage-Instructions).

These are the things one would need to do even if he is working in dev env, I think they should go on landing page.

**Comment by sarupbanskota** [comment]
put them on the wiki for now.

**Comment by sonalkr132** [comment]
What about the changes required in deployment on openshift?

**Comment by sonalkr132** [comment]
We should create [get involved](https://github.com/glittergallery/GlitterGallery/wiki/getinvolved) page now. We should tell contributors that they need to run `rubocop`, `haml-lint` and `rspec` before they submit a PR and where they can find help if they are having problem passing anyone of them.

**Comment by sonalkr132** [comment]
Hey we already have [get involved!](https://github.com/glittergallery/GlitterGallery/wiki/Get-Involved!). I was looking at one in [home](https://github.com/glittergallery/GlitterGallery/wiki) page of wiki. There link is broken, I guess we need to fix that too.

**Comment by sarupbanskota** [comment]
@sonalkr132, deployment changes on the README, and feel free to update the wiki :-)

**Comment by sonalkr132** [comment]
Not relevant anymore. Check #323 and #308 instead.
