### ISSUE TITLE
test: Redirected to login page for JS requests

### ISSUE THREAD

**Issue by sonalkr132** [glittergallery/GlitterGallery#279]
This is the result of two consecutive runs of `rspec` without changing anything in files.
![screenshot from 2015-03-c24 20 22 42](https://cloud.githubusercontent.com/assets/7680662/6806415/99f680ae-d26e-11e4-9ea3-de8eb22bd3cf.png)

During first run it failed and in next one it passed!
Am I the only one who is seeing this? Could this be an issue of my local env?

**Comment by Alwahsh** [comment]
No, I have it too and it seems like a problem with webkit... I'm planning to have a proper look at it once I get some time unless @rohitpaulk fixed it first :P.

**Comment by rohitpaulk** [comment]
I tried running like 5 times in a row - and I couldn't see an error, so I just assumed that what we had was working :P

**Comment by sonalkr132** [comment]
closed by: #305
