### ISSUE TITLE
Issue create redirects to dashboard of projects

### ISSUE THREAD

**Issue by sonalkr132** [glittergallery/GlitterGallery#285]
Create method of Issue has:
```Ruby
redirect_to(dashboard_path)
```
Shouldn't it redirect to issue show page?

**Comment by Alwahsh** [comment]
yeah... I actually made it work like that in a PR that I didn't yet upload :)

**Comment by sonalkr132** [comment]
oh can you reference PR here? I will close it.

**Comment by Alwahsh** [comment]
I don't think you should close it... They might have some reason for making it that way so I suggest you leave this open till they confirm.

**Comment by mecyborg** [comment]
I was also wondering why its like that but it can be intentional, so please wait till they confirm.

**Comment by sarupbanskota** [comment]
It should redirect to issue page, correct.

Sarup

**Comment by Alwahsh** [comment]
This can be closed now.

**Comment by sonalkr132** [comment]
fixed: #292
