### ISSUE TITLE
Image won't show on user/project_name

### ISSUE THREAD

**Issue by chi6rag** [glittergallery/GlitterGallery#299]
I visited the project show page here:
http://demo.glittergallery.net/chi6rag/EdenGarden

Result: broken image

![image_wont_show](http://res.cloudinary.com/chi6rag/image/upload/v1432205832/GlitterGallery/gg_image_wont_show.png)

**Comment by sonalkr132** [comment]
This problem should not exist on current master either. It was fixed in #264. I will try to deploy and confirm.

**Comment by sonalkr132** [comment]
this can be closed too!
