### ISSUE TITLE
File type stats layout

### ISSUE THREAD

**Issue by sonalkr132** [glittergallery/GlitterGallery#306]
Following is all I can think of when it comes to layout of filetype of a particular project:
![screenshot from 2015-08-2s4 23 13 23](https://cloud.githubusercontent.com/assets/7680662/9458739/12c087d6-4b10-11e5-9b8e-41f74b212ca8.png)

Does it feel too githuby? I am open to any other suggestions.

**Comment by sarupbanskota** [comment]
@sonalkr132 it looks fine for now :) we can always improve later.

**Comment by sonalkr132** [comment]
I ended up making this:
![screenshot from 2015-09-06 10 30 35](https://cloud.githubusercontent.com/assets/7680662/9702587/8f93a31c-5482-11e5-8fd2-a98ddd0e360a.png)
Github uses css, I have used canvas. I hope [canvas.js](https://github.com/sonalkr132/GlitterGallery/blob/2b1b966f6d61184158acda425fdf03dc0275245e/app/assets/javascripts/canvas.js) file is not too big.

**Comment by sonalkr132** [comment]
closed by: #305
