### ISSUE TITLE
Previous work on image annotation

### ISSUE THREAD

**Issue by sonalkr132** [glittergallery/GlitterGallery#309]
Currently [jquery.annotate.js](https://github.com/glittergallery/GlitterGallery/blob/master/app/assets/javascripts/jquery.annotate.js) exists in our repo, which isn't really surving any purpose. It was introduced in ecbfc51 and it's dependencies (images?) were removed in c8b2d0d. Did it use to work? Commit message reads: "Add *non-persistent flickr notes* to static images". Is no database support only issue here? @EmilyDirsh Looks like you were working on it. I most certainly would not want to reinvent the wheel here.

**Comment by sonalkr132** [comment]
> I have come across some annotation issue and easiest fix is that we convert svg files to png. When [annotorious](https://github.com/annotorious/annotorious) makes ajax call for annotation to be stored in db, it sends json which contains the complete image tag (along with some other information). We need that information so that we can redraw all the annotation when someone reloads the page.
Problem with that our image tags are just huge since it doesn't contain image as a file but string/blob. ie our src is of the form:
"data:image/svg+xml;base64, #{Base64.encode64(image[:data])}"
 This is a huge performance issue as basically whole image (size can be as large as a couple of MBs) is sent over network and every annotation will have to wait until all the data is sent back. Beside this, json returned is also stored in DB so we will end up storing every image in database.
One solution can be that we generate files for blob view. This way src will just contain a filename. Unfortunately, this doesn't end here, I have been unable to generate svg files from blob. Check [this question](http://stackoverflow.com/questions/32942402/rmagic-write-blob-string-to-svg). I was hoping we convert svg to png instead(this one works). May be we can add a button for raw view of blob and we don't have to support annotation there. This way we can also extend our supported files to everything supported by rmagic. Browser support for different file types isn't very great so in the end we will have to do it anyway. Most of them [support only jpeg and png](https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support).

**Comment by sarupbanskota** [comment]
Posting this based on the email you sent out to the design team mailer. 

Yes, you can serve the images as png, as long as you maintain their svg nature in the repo itself.

**Comment by sonalkr132** [comment]
Closed by #311
