### ISSUE TITLE
Image update with a different filename

### ISSUE THREAD

**Issue by sonalkr132** [glittergallery/GlitterGallery#312]
What happens when a user tries to update an image from web interface is kinda confusing. if `filename.png` is updated with another image `anothername.png`,  updated image is still called `filename.png`.

Is this desired behavior?

**Comment by sarupbanskota** [comment]
Yup.

An "update" to a file is essentially content update. Later on, we could support renaming of files, but that's different from the concept you're hinting at :-)

If a person wants to: 
1. update content of one file, based on content of another file in local, he/she can do an *update*
2. update the name of the current file, use the rename functionality (#TODO)
3. add a file with another name and different content. then he/she can create a new file
4. replace current file with another name and different content, then he/she can do 1 followed by 2
