### ISSUE TITLE
After sign in path

### ISSUE THREAD

**Issue by sonalkr132** [glittergallery/GlitterGallery#314]
Right now after sign in path is dashboard and it is quite boring:
![screenshot from 2015-10-26 22 07 38](https://cloud.githubusercontent.com/assets/7680662/10735685/3d63a996-7c2f-11e5-95c7-89b7b2a9c56d.png)

Even that one "get me started" button take user to user_edit path (why??!!) Also, this dashboard page is not navigable. There are no link on app which will take you there. I propose that we lose dashboard page and set after sign in path to user/projects if user has projects and to root path (exploration page) if they don't.

**Comment by sarupbanskota** [comment]
@sonalkr132 There were more comprehensive plans for the dashboard page, but we obviously couldn't get to them. I won't propose losing the dashboard page altogether, but if you have a flow that works, you can change the redirects and make pages you think aren't necessary not show up unless the user demands them.
