### ISSUE TITLE
Associate comment with projects

### ISSUE THREAD

**Issue by sonalkr132** [glittergallery/GlitterGallery#315]
Existing problem with our comments is that there is no way to find project of comments made on `blob`, `tree` and `commit`. This creates problem when we are serving notification. It is crucial that we know which project should a user be redirected when they click on notification link like:
* [user1 has commented on fancy_project's blob/commit/tree](#)

I think it can be solved if we project_id to all the comments. It will be useless information for comments on issues (as relation between issue and projects already exists), oh well!

@rohitpaulk Your two cents?

Previous discussion [here](https://github.com/glittergallery/GlitterGallery/pull/254)

**Comment by sonalkr132** [comment]
So this is really disappointing :disappointed:
Adding project_id is not going to be enough for fixing all of our problems. Have a look at a blob url (to which user will need to be send for comments on that blob):
`domain.name/addie/fancy_project/blob/eea87f45d7ed9726267222d8050f444f475b4d5d/pictures/some-cats.jpeg`

It is of the form:  `domain.name/username/projectname/blob/commit_id/path_to_blob`
Comments only have the blob id and it is going to very expensive to figure out `path` and `commit_id`. Checkout [#541](https://github.com/libgit2/rugged/issues/541).
Tableless model suggestion of @Alwahsh  is probably not going to work either cause we don't just need to send out mails but we need those links to stick around for activities tab of user. Only solution I have in my mind is that we store the complete link `/username/projectname/blob/commit_id/path_to_blob` in notification model. It will definitely be cheaper and much less complex than preparing the url.

**Note**: Same explanation is valid for comments on tree.

**Comment by sarupbanskota** [comment]
@sonalkr132 I don't have much background on this issue either, but if you have a solution that works for the time being and that helps you complete the feature, let lack of response not block you from carrying forward with it :-)

**Comment by sonalkr132** [comment]
Closed from #319 

redirect url is being stored in notification and annotation model as building them later on was way too expensive.
