### ISSUE TITLE
Installation instructions: Wiki or installation.md?

### ISSUE THREAD

**Issue by sonalkr132** [glittergallery/GlitterGallery#323]
I am writing installation instructions. It will cover things like installing native dependencies of gems we are using, setting up postgres and gitlab-shell, files one needs to edit to get everything running in their local env etc.

Normally it is written in a file called `installation.md` (which exits in the repository itself). However we maintain wiki for these sort of thing. for ex: [Usage Instructions](https://github.com/glittergallery/GlitterGallery/wiki/Usage-Instructions)

**Comment by sarupbanskota** [comment]
Let's use the wiki for now :-) That could come under "documenting" which
will receive relatively frequent updates and might polluting the repo.

Sarup

**Comment by sonalkr132** [comment]
Installation instructions exist at https://github.com/glittergallery/GlitterGallery/wiki/Installation-Instructions
