### ISSUE TITLE
Generic file icon for unsupported file types

### ISSUE THREAD

**Issue by sonalkr132** [glittergallery/GlitterGallery#324]
I was hoping that until we support more format, we should show user a generic file icon instead of broken image. However, I am not able to find any usable icon (with appropriate license) on web and I really don't want to make one on my own.

**Comment by sarupbanskota** [comment]
https://thenounproject.com/search/?q=file%20type try these for file icons?

Sarup

**Comment by sonalkr132** [comment]
Yeah, those can work It is asking for purchase or credit. Does that mean we need to mention creator's name in readme?

**Comment by sonalkr132** [comment]
closed from #328
