### ISSUE TITLE
create awesome landing page for GlitterGallery

### ISSUE THREAD

**Issue by sarupbanskota** [glittergallery/GlitterGallery#63]
We need a nice landing page describing features, instructions about setting up, contact information, etc

**Comment by mecyborg** [comment]
Hi, I can make a landing page for GG. Should I start ?

**Comment by sarupbanskota** [comment]
n Fri, Mar 6, 2015 at 10:55 PM, Nikunj Gupta <notifications@github.com>
wrote:

> Hi, I can make a landing page for GG. Should I start ?
>

If you'd like to, why not? :-) let us know how you plan to go about it
though, before you start.

**Comment by mecyborg** [comment]
I will use Bootstrap for this. As GG is based on rails, there will be no issues in integration.

**Comment by rohitpaulk** [comment]
I really don't see the point in another landing page, http://www.glittergallery.net/ is good enough IMO.
